windows:
  - position_x: 0
    position_y: 0
    width: 1920
    height: 1080
  - position_x: 1920
    position_y: 0
    width: 1920
    height: 1080
stations:
  - name: Durlacher Tor / KIT-Campus Süd
    stop_points:
      - stop_point_ref: de:08212:3
        prefix: ""
        suffix: ""
      - stop_point_ref: de:08212:1001
        prefix: ""
        suffix: " (U)"
credentials:
  url: https://projekte.kvv-efa.de/YOUR-URL/trias
  requestor_ref:  YOUR-REQUESTOR_REF