displays:
  1: 
    window:
      position_x: 0
      position_y: 0
      width: 1720
      height: 1440
  2: 
    window:
      position_x: 1720
      position_y: 0
      width: 1720
      height: 1440
credentials:
  url: https://projekte.kvv-efa.de/YOUR-URL/trias
  requestor_ref:  YOUR-REQUESTOR_REF