name: Run Python Script on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: [self-hosted, Z10-Treppenhaus]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Upgrade PIP
        run: |
          python -m pip install --upgrade pip

      - name: Update / Install requirements
        run: |
          pip install --upgrade -r requirements.txt

      - name: Run Python script
        run: |
          source venv/bin/activate
          python your_script.py
